# Generated manually
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('operator', 'Оператор'), ('engineer', 'Інженер'), ('chief', 'Керівник цеху'), ('deputy_production', 'Заступник з виробництва та планування'), ('deputy_engineering', 'Заступник з інжинірингу')], default='operator', max_length=32)),
                ('can_approve_reports', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(name='Equipment', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=255)), ('station', models.CharField(max_length=255)), ('type', models.CharField(choices=[('pump', 'Насос'), ('dredger', 'Землесос')], max_length=16)), ('is_active', models.BooleanField(default=True))]),
        migrations.CreateModel(name='LevelVolumeTable', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('reservoir_name', models.CharField(choices=[('tailing_1', 'Хвостосховище 1'), ('tailing_2', 'Хвостосховище 2'), ('buffer_pond', 'Буферний ставок'), ('water_pond', 'Ставок об. вод.'), ('emergency_tank', 'Аварійна ємність')], max_length=32)), ('level_cm', models.IntegerField()), ('volume_m3', models.DecimalField(decimal_places=2, max_digits=14))], options={'ordering': ('reservoir_name', 'level_cm'), 'unique_together': {('reservoir_name', 'level_cm')}}),
        migrations.CreateModel(name='MaintenanceRecord', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('work_type', models.CharField(choices=[('TO', 'ТО'), ('PR', 'ПР'), ('KR', 'КР')], max_length=2)), ('description', models.TextField()), ('contractor_category', models.CharField(choices=[('own', 'Власні сили'), ('internal', 'Внутрішні підрядники'), ('third_party', 'Треті особи')], max_length=16)), ('external_services_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)), ('work_date', models.DateField(default=django.utils.timezone.localdate)), ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to=settings.AUTH_USER_MODEL)), ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='operations.equipment'))]),
        migrations.CreateModel(name='ShiftReport', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('shift_date', models.DateField()), ('shift_number', models.PositiveSmallIntegerField()), ('is_locked', models.BooleanField(default=False)), ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_reports', to=settings.AUTH_USER_MODEL))], options={'ordering': ('-shift_date', '-shift_number'), 'unique_together': {('shift_date', 'shift_number', 'author')}}),
        migrations.CreateModel(name='TmcCatalog', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('nomenclature_id', models.CharField(max_length=64, unique=True)), ('name', models.CharField(max_length=255)), ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=14)), ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=14))]),
        migrations.CreateModel(name='ReservoirLevel', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('reservoir_name', models.CharField(choices=[('tailing_1', 'Хвостосховище 1'), ('tailing_2', 'Хвостосховище 2'), ('buffer_pond', 'Буферний ставок'), ('water_pond', 'Ставок об. вод.'), ('emergency_tank', 'Аварійна ємність')], max_length=32)), ('level_start_m', models.DecimalField(decimal_places=2, max_digits=8)), ('level_end_m', models.DecimalField(decimal_places=2, max_digits=8)), ('calc_volume_start', models.DecimalField(decimal_places=2, default=0, max_digits=14)), ('calc_volume_end', models.DecimalField(decimal_places=2, default=0, max_digits=14)), ('shift_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservoir_levels', to='operations.shiftreport'))]),
        migrations.CreateModel(name='ProductionMetrics', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('vol_water', models.DecimalField(decimal_places=2, max_digits=14)), ('vol_slurry', models.DecimalField(decimal_places=2, max_digits=14)), ('vol_dredge', models.DecimalField(decimal_places=2, default=0, max_digits=14)), ('vol_dns3', models.DecimalField(decimal_places=2, default=0, max_digits=14)), ('vol_emergency_drop', models.DecimalField(decimal_places=2, default=0, max_digits=14)), ('energy_abs', models.DecimalField(decimal_places=2, max_digits=14)), ('shift_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_metrics', to='operations.shiftreport'))]),
        migrations.CreateModel(name='EquipmentTimeLog', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('work_hours', models.DecimalField(decimal_places=2, max_digits=5)), ('reserve_hours', models.DecimalField(decimal_places=2, max_digits=5)), ('downtime_mech', models.DecimalField(decimal_places=2, max_digits=5)), ('downtime_el', models.DecimalField(decimal_places=2, max_digits=5)), ('downtime_tech', models.DecimalField(decimal_places=2, max_digits=5)), ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_logs', to='operations.equipment')), ('shift_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_time_logs', to='operations.shiftreport'))]),
        migrations.CreateModel(name='TmcWriteOff', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('quantity', models.DecimalField(decimal_places=2, max_digits=14)), ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)), ('writeoff_date', models.DateField(default=django.utils.timezone.localdate)), ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tmc_writeoffs', to=settings.AUTH_USER_MODEL)), ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writeoffs', to='operations.tmccatalog')), ('maintenance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tmc_writeoffs', to='operations.maintenancerecord'))]),
    ]
